/usr/bin/python2.6: can't open file '/home/djcdn/service/convert_worker.py': [Errno 2] No such file or directory
/usr/bin/python: can't open file '/home/djcdn/service/convert_worker.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 7, in <module>
    from . import config
ValueError: Attempted relative import in non-package
Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 7, in <module>
    from . import config
ValueError: Attempted relative import in non-package
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 14:02:43 04/03/16 UTC

Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 83, in <module>
    channel.start_consuming()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 51, in rabbbit_callback
    subprocess.call(command)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 14:04:42 04/03/16 UTC

['ffmpeg', '-loglevel', 'quiet', '-i', u'/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141.mp3', '-ab', u'192k', '-ar', '44800', '-vn', u'/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3']
Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 84, in <module>
    channel.start_consuming()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 52, in rabbbit_callback
    subprocess.call(command)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 1, in <module>
    import pika
ImportError: No module named pika
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 17:13:56 04/03/16 UTC

['ffmpeg', '-loglevel', 'quiet', '-i', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141.mp3', '-ab', '192k', '-ar', '44800', '-vn', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3']

Convert Successfull to : /home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3

Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 84, in <module>
    channel.start_consuming()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 56, in rabbbit_callback
    insert_media_link(dbMongo, params)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 27, in insert_media_link
    client = connect_mongo_db(dbConfig, params)
NameError: global name 'connect_mongo_db' is not defined
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 17:18:21 04/03/16 UTC

['ffmpeg', '-loglevel', 'quiet', '-i', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141.mp3', '-ab', '192k', '-ar', '44800', '-vn', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3']
File '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3' already exists. Overwrite ? [y/N] 
Convert Successfull to : /home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3

Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 84, in <module>
    channel.start_consuming()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 56, in rabbbit_callback
    insert_media_link(dbMongo, params)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 33, in insert_media_link
    db.media.update_one(
NameError: global name 'db' is not defined
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 17:19:16 04/03/16 UTC

['ffmpeg', '-loglevel', 'quiet', '-i', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141.mp3', '-ab', '192k', '-ar', '44800', '-vn', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3']
File '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3' already exists. Overwrite ? [y/N] 
Convert Successfull to : /home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3

Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 84, in <module>
    channel.start_consuming()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 56, in rabbbit_callback
    insert_media_link(dbMongo, params)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 37, in insert_media_link
    field_name: field_value
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 832, in update_one
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 716, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: No servers found yet
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 17:21:41 04/03/16 UTC

['ffmpeg', '-loglevel', 'quiet', '-i', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141.mp3', '-ab', '192k', '-ar', '44800', '-vn', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3']

Convert Successfull to : /home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3

Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 84, in <module>
    channel.start_consuming()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 56, in rabbbit_callback
    insert_media_link(dbMongo, params)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 37, in insert_media_link
    field_name: field_value
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 832, in update_one
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 716, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: No servers found yet
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 17:23:33 04/03/16 UTC

['ffmpeg', '-loglevel', 'quiet', '-i', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141.mp3', '-ab', '192k', '-ar', '44800', '-vn', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3']
File '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3' already exists. Overwrite ? [y/N] 
Convert Successfull to : /home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3

Database(MongoClient(host=['dj.pro.vn:27017'], document_class=dict, tz_aware=False, connect=True), u'djpro')
Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 85, in <module>
    channel.start_consuming()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 57, in rabbbit_callback
    insert_media_link(dbMongo, params)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 38, in insert_media_link
    field_name: field_value
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 832, in update_one
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 716, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: No servers found yet
 [*] Waiting for messages. To exit press CTRL+C

 ----------------- Convert file ------------

In time: 17:25:19 04/03/16 UTC

['ffmpeg', '-loglevel', 'quiet', '-i', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141.mp3', '-ab', '192k', '-ar', '44800', '-vn', '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3']
File '/home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3' already exists. Overwrite ? [y/N] 
Convert Successfull to : /home/djcdn/public_html/public/media/2016/04_03/song/test_128_1459690293_1141_1459691532_192k.mp3

Database(MongoClient(host=['123.30.174.167:27017'], document_class=dict, tz_aware=False, connect=True), u'djpro')
Traceback (most recent call last):
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 85, in <module>
    channel.start_consuming()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 57, in rabbbit_callback
    insert_media_link(dbMongo, params)
  File "/home/djcdn/public_html/service/Worker/convert_worker.py", line 38, in insert_media_link
    field_name: field_value
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 832, in update_one
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 716, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: No servers found yet
